### ISSUE TITLE
初次登陆报错

### ISSUE THREAD

**Issue by JunDeer** [Sorosliu1029/Jike-Metro#19]
c = jike.JikeClient()
调用
utils.login()
res = requests.get(ENDPOINTS['create_session'])
报错:
requests.exceptions.SSLError: HTTPSConnectionPool(host='app.jike.ruguoapp.com', port=443): Max retries exceeded with url: /sessions.create (Caused by SSLError(CertificateError("hostname 'app.jike.ruguoapp.com' doesn't match either of '*.ruguoapp.com', 'ruguoapp.com'",),))

**Comment by Sorosliu1029** [comment]
项目不再维护了。

源码也是比较简单易懂的，可以自己尝试修改。
